### ISSUE TITLE
リンク切れチェックのrakeタスクがエラー

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#1685]
```sh
% heroku run rake bootcamp:find_broken_link -a bootcamp-fjord-jp

rake aborted!
Errno::ECONNREFUSED: Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80)
/app/app/models/link_checker.rb:40:in `block (2 levels) in access_url'
/app/app/models/link_checker.rb:38:in `map'
/app/app/models/link_checker.rb:38:in `block in access_url'
/app/app/models/link_checker.rb:37:in `map'
/app/app/models/link_checker.rb:37:in `access_url'
/app/app/models/link_checker.rb:66:in `check_url'
/app/app/models/link_checker.rb:8:in `notify_error_url'
/app/lib/tasks/bootcamp.rake:8:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/app/bin/bundle:5:in `load'
/app/bin/bundle:5:in `<main>'

Caused by:
Errno::ECONNREFUSED: Connection refused - connect(2) for nil port 80
/app/app/models/link_checker.rb:40:in `block (2 levels) in access_url'
/app/app/models/link_checker.rb:38:in `map'
/app/app/models/link_checker.rb:38:in `block in access_url'
/app/app/models/link_checker.rb:37:in `map'
/app/app/models/link_checker.rb:37:in `access_url'
/app/app/models/link_checker.rb:66:in `check_url'
/app/app/models/link_checker.rb:8:in `notify_error_url'
/app/lib/tasks/bootcamp.rake:8:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/app/bin/bundle:5:in `load'
/app/bin/bundle:5:in `<main>'
Tasks: TOP => bootcamp:find_broken_link
(See full trace by running task with --trace)
** [NewRelic][2020-06-26 14:35:06 +0900 run.* (4)] INFO : Starting Agent shutdown
```

**Comment by komagata** [comment]
@HiroVodka こちら不明点があったら作成された @mikihito-h さんに聞くのが良いかもです〜。

**Comment by HiroVodka** [comment]
@komagata 
ありがとうございます〜！
承知しました💪

**Comment by HiroVodka** [comment]
@komagata 本番環境がherokuから移行するみたいですがこちらのIssueはこのまま取り組んで大丈夫でしょうか？？🤔

**Comment by komagata** [comment]
@HiroVodka はい、プログラムの中身に影響はないと思うのでお願いします〜

**Comment by HiroVodka** [comment]
@komagata 承知しました〜！
こちらペアプロお願いしたいんですがよろしいでしょうか？？

**Comment by komagata** [comment]
@HiroVodka はい、大丈夫です。下記から大丈夫な時間を選択いただければと思います。

https://komagata.youcanbook.me/

**Comment by HiroVodka** [comment]
9/24の14:00~で予約させていただきました🙇‍♂️
よろしくお願いします〜

**Comment by komagata** [comment]
@HiroVodka 確認しました。よろしくお願いします〜！

**Comment by komagata** [comment]
完了
