### ISSUE TITLE
db:migrateでデプロイが失敗している。PG::DependentObjectsStillExist: ERROR

### ISSUE THREAD

**Issue by bluerabbit** [fjordllc/bootcamp#2022]
## 概要

#2010 以降のdb:migrateでデプロイが失敗しています。

```
== 20201014114543 RemoveStudyPlaceFromUsers: migrating ========================
-- remove_column(:users, :study_place, :integer)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DependentObjectsStillExist: ERROR:  cannot drop column study_place of table users because other objects depend on it
DETAIL:  view students depends on column study_place of table users
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `exec'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `block (2 levels) in execute'
/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:91:in `block in execute'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
```

**Comment by bluerabbit** [comment]
@komagata 

studentsのviewがDBにはありますが、migrationファイルには無いですか？schema.rbに見当たらない。
studentsのviewは使っていますか？

**Comment by bluerabbit** [comment]
## studentsのviewのDDL

```sql
 SELECT users.id,
    users.login_name,
    users.email,
    users.crypted_password,
    users.salt,
    users.created_at,
    users.updated_at,
    users.remember_me_token,
    users.remember_me_token_expires_at,
    users.twitter_account,
    users.facebook_url,
    users.blog_url,
    users.company_id,
    users.description,
    users.accessed_at,
    users.github_account,
    users.adviser,
    users.nda,
    users.slack_account,
    users.reset_password_token,
    users.reset_password_token_expires_at,
    users.reset_password_email_sent_at,
    users.mentor,
    users.graduated_on,
    users.course_id,
    users.retired_on,
    users.admin,
    users.job,
    users.organization,
    users.os,
    users.study_place,
    users.experience,
    users.free,
    users.trainee,
    users.retire_reason,
    users.job_seeking,
    users.customer_id,
    users.subscription_id,
    users.mail_notification,
    users.prefecture_code,
    users.job_seeker,
    users.slack_participation,
    users.github_collaborator,
    users.officekey_permission,
    users.github_id,
    users.satisfaction,
    users.opinion,
    users.retire_reasons,
    users.name,
    users.name_kana,
    (users.created_at)::date AS created_on
   FROM users
  WHERE ((users.admin = false) AND (users.mentor = false) AND (users.adviser = false) AND (users.trainee = false) AND (users.free = false));
```

study_placeを消せば良さそう。

**Comment by komagata** [comment]
修正してデプロイしました。
