### ISSUE TITLE
プラクティス一覧ページにて、着手中のプラクティスがない場合、次に手を付けるべきプラクティスのカテゴリーが自動で表示されない

### ISSUE THREAD

**Issue by unstoppa61e** [fjordllc/bootcamp#3783]
## 概要
現状、プラクティス一覧ページを開いた際、着手中のプラクティスがある場合は、そのプラクティスが所属するカテゴリーが表示されるようになっている。
しかし、例えば着手中のプラクティスが完了するなどして、着手中のプラクティスがなくなった場合、プラクティス一覧ページの最上部が表示されるため、着手したいプラクティスの箇所までスクロールしなくてはならない。

## 再現手順

1. 着手中のプラクティスがない状態にする
2. 画面左側のタブより、「プラクティス」をクリックし、プラクティス一覧ページへ移動する
3. ページの先頭が表示される

## 期待される振る舞い

着手中のプラクティスがないならば、「未着手」のプラクティスのうち先頭のプラクティスが所属するカテゴリーが表示される

## 関連Issue

Ref: #3647, #3784

**Comment by machida** [comment]
> 着手中のプラクティスがないならば、「未着手」のプラクティスのうち先頭のプラクティスが所属するカテゴリーが表示される

言い換えると、

完了したプラクティスのカテゴリーの次のカテゴリーまでスクロールされるようにしたい。

**Comment by komagata** [comment]
@unstoppa61e これって個人の希望であってバグ（不具合）とはちょっと違う気がするのでバグは外しておきますね〜

**Comment by Paru871** [comment]
@komagata @machida @unstoppa61e 
皆さんにメンションで失礼します🙇🏻‍♀️仕様の確認をさせていただきたく、お願いします。

通常プラクティスは上から順番に取り組んでいくことになっていますが、稀に意識的に、プラクティスをスキップして先に進む受講生もいます。
例えば極端な画像ですが、このような場合、
【A案】「未着手」のプラクティスの最上段のプラクティスが所属するカテゴリー名までスクロールした状態で表示
【B案】「提出」または「完了」の最下段のプラクティスの、次のプラクティスが所属するカテゴリー名までスクロールした状態で表示
![スクリーンショット 2021-12-22 17 02 42](https://user-images.githubusercontent.com/82434093/147060280-b92d48b4-8c18-44eb-85b4-a04d4aa77086.png)

上記2案のどちらのイメージで進めていけばよろしいでしょうか。
ご指示またはアイディアをいただけましたら助かります。
よろしくお願いします🙏🙇🏻‍♀️

**Comment by unstoppa61e** [comment]
@Paru871 
僕は A 案のつもりでした。
その方が、未着手のプラクティスがあることを失念してしまうケースを防げるためです。
ただ、特にこだわりはございませんので、B 案でも大丈夫です。

**Comment by machida** [comment]
@Paru871 
ありがとうございますー
着手中がない場合は、A案でお願いしますー🙏

**Comment by Paru871** [comment]
@machida @unstoppa61e 
早速ご指示ありがとうございます！それではA案で進めますー。
頑張ります💪

**Comment by Paru871** [comment]
プルリク#3924にて開発を進めてきましたが、ローカル・ステージング環境まではOKで本番環境では正しく表示されないため、ローカル・ステージング環境にて再度調査を行います。

**Comment by komagata** [comment]
:memo: こちら質問タイムで @Paru871 さんと話しました。
本番環境でしか起こらないちょっと難しい問題のようなので僕が担当して修正します〜。

**Comment by Paru871** [comment]
@komagata 
ありがとうございます。お手数をおかけしますが、よろしくお願いします。
本番環境で意図した動作にならないパターンの説明や動作テストなどできることがありましたらやらせてください！

こちら、先日の質問タイムでお見せできなかった、「ローカル環境で実行時にターミナルに表示された各メソッドのSQL文」です。(もう不要かと思いましたが念の為お知らせします。)
```
 Practice Load (2.7ms)  SELECT "practices".* FROM "practices" INNER JOIN "learnings" ON "practices"."id" = "learnings"."practice_id" WHERE "learnings"."user_id" = $1 AND "learnings"."status" = $2  [["user_id", 679998234], ["status", 1]]
  ↳ app/models/user.rb:586:in `category_active_or_unstarted_practice'

Course Load (0.8ms)  SELECT "courses".* FROM "courses" WHERE "courses"."id" = $1 LIMIT $2  [["id", 829913840], ["LIMIT", 1]]
  ↳ app/models/user.rb:556:in `practices'

Practice Load (6.3ms)  SELECT "practices".* FROM "practices" INNER JOIN "categories_practices" ON "practices"."id" = "categories_practices"."practice_id" INNER JOIN "categories" ON "categories_practices"."category_id" = "categories"."id" INNER JOIN "courses_categories" ON "categories"."id" = "courses_categories"."category_id" WHERE "courses_categories"."course_id" = $1 ORDER BY "categories_practices"."position" ASC, "courses_categories"."position" ASC, categories.position, practices.position  [["course_id", 829913840]]
  ↳ app/models/user.rb:609:in `unstarted_practices'

Practice Load (5.4ms)  SELECT "practices".* FROM "practices" INNER JOIN "categories_practices" ON "practices"."id" = "categories_practices"."practice_id" INNER JOIN "categories" ON "categories_practices"."category_id" = "categories"."id" INNER JOIN "courses_categories" ON "categories"."id" = "courses_categories"."category_id" INNER JOIN "learnings" ON "learnings"."practice_id" = "practices"."id" WHERE "courses_categories"."course_id" = $1 AND "learnings"."user_id" = $2 AND ("learnings"."status" = $3 OR "learnings"."status" = $4 OR "learnings"."status" = $5) ORDER BY "categories_practices"."position" ASC, "courses_categories"."position" ASC, categories.position, practices.position  [["course_id", 829913840], ["user_id", 679998234], ["status", 1], ["status", 2], ["status", 3]]
  ↳ app/models/user.rb:609:in `unstarted_practices'

CACHE Practice Load (0.0ms)  SELECT "practices".* FROM "practices" INNER JOIN "categories_practices" ON "practices"."id" = "categories_practices"."practice_id" INNER JOIN "categories" ON "categories_practices"."category_id" = "categories"."id" INNER JOIN "courses_categories" ON "categories"."id" = "courses_categories"."category_id" WHERE "courses_categories"."course_id" = $1 ORDER BY "categories_practices"."position" ASC, "courses_categories"."position" ASC, categories.position, practices.position  [["course_id", 829913840]]
  ↳ app/models/user.rb:609:in `unstarted_practices'

CACHE Practice Load (0.0ms)  SELECT "practices".* FROM "practices" INNER JOIN "categories_practices" ON "practices"."id" = "categories_practices"."practice_id" INNER JOIN "categories" ON "categories_practices"."category_id" = "categories"."id" INNER JOIN "courses_categories" ON "categories"."id" = "courses_categories"."category_id" INNER JOIN "learnings" ON "learnings"."practice_id" = "practices"."id" WHERE "courses_categories"."course_id" = $1 AND "learnings"."user_id" = $2 AND ("learnings"."status" = $3 OR "learnings"."status" = $4 OR "learnings"."status" = $5) ORDER BY "categories_practices"."position" ASC, "courses_categories"."position" ASC, categories.position, practices.position  [["course_id", 829913840], ["user_id", 679998234], ["status", 1], ["status", 2], ["status", 3]]
  ↳ app/models/user.rb:609:in `unstarted_practices'

Category Load (1.4ms)  SELECT "categories".* FROM "categories" INNER JOIN "categories_practices" ON "categories"."id" = "categories_practices"."category_id" WHERE "categories_practices"."practice_id" = $1 ORDER BY "categories_practices"."position" ASC LIMIT $2  [["practice_id", 315059988], ["LIMIT", 1]]
  ↳ app/models/user.rb:620:in `category_having_unstarted_practice'

CACHE Practice Load (0.0ms)  SELECT "practices".* FROM "practices" INNER JOIN "categories_practices" ON "practices"."id" = "categories_practices"."practice_id" INNER JOIN "categories" ON "categories_practices"."category_id" = "categories"."id" INNER JOIN "courses_categories" ON "categories"."id" = "courses_categories"."category_id" WHERE "courses_categories"."course_id" = $1 ORDER BY "categories_practices"."position" ASC, "courses_categories"."position" ASC, categories.position, practices.position  [["course_id", 829913840]]
  ↳ app/models/user.rb:609:in `unstarted_practices'

CACHE Practice Load (0.0ms)  SELECT "practices".* FROM "practices" INNER JOIN "categories_practices" ON "practices"."id" = "categories_practices"."practice_id" INNER JOIN "categories" ON "categories_practices"."category_id" = "categories"."id" INNER JOIN "courses_categories" ON "categories"."id" = "courses_categories"."category_id" INNER JOIN "learnings" ON "learnings"."practice_id" = "practices"."id" WHERE "courses_categories"."course_id" = $1 AND "learnings"."user_id" = $2 AND ("learnings"."status" = $3 OR "learnings"."status" = $4 OR "learnings"."status" = $5) ORDER BY "categories_practices"."position" ASC, "courses_categories"."position" ASC, categories.position, practices.position  [["course_id", 829913840], ["user_id", 679998234], ["status", 1], ["status", 2], ["status", 3]]
  ↳ app/models/user.rb:609:in `unstarted_practices'

CACHE Practice Load (0.0ms)  SELECT "practices".* FROM "practices" INNER JOIN "categories_practices" ON "practices"."id" = "categories_practices"."practice_id" INNER JOIN "categories" ON "categories_practices"."category_id" = "categories"."id" INNER JOIN "courses_categories" ON "categories"."id" = "courses_categories"."category_id" WHERE "courses_categories"."course_id" = $1 ORDER BY "categories_practices"."position" ASC, "courses_categories"."position" ASC, categories.position, practices.position  [["course_id", 829913840]]
  ↳ app/models/user.rb:609:in `unstarted_practices'

CACHE Practice Load (0.0ms)  SELECT "practices".* FROM "practices" INNER JOIN "categories_practices" ON "practices"."id" = "categories_practices"."practice_id" INNER JOIN "categories" ON "categories_practices"."category_id" = "categories"."id" INNER JOIN "courses_categories" ON "categories"."id" = "courses_categories"."category_id" INNER JOIN "learnings" ON "learnings"."practice_id" = "practices"."id" WHERE "courses_categories"."course_id" = $1 AND "learnings"."user_id" = $2 AND ("learnings"."status" = $3 OR "learnings"."status" = $4 OR "learnings"."status" = $5) ORDER BY "categories_practices"."position" ASC, "courses_categories"."position" ASC, categories.position, practices.position  [["course_id", 829913840], ["user_id", 679998234], ["status", 1], ["status", 2], ["status", 3]]
  ↳ app/models/user.rb:609:in `unstarted_practices'

CACHE Category Load (0.0ms)  SELECT "categories".* FROM "categories" INNER JOIN "categories_practices" ON "categories"."id" = "categories_practices"."category_id" WHERE "categories_practices"."practice_id" = $1 ORDER BY "categories_practices"."position" ASC LIMIT $2  [["practice_id", 315059988], ["LIMIT", 1]]
  ↳ app/models/user.rb:620:in `category_having_unstarted_practice'
```

**Comment by komagata** [comment]
:memo: 調査した項目

- そもそもカテゴリー、プラクティスのソートが間違っているところがアプリに色々ある。
- 現実装のソート順（courses_categories.position, categories_practices.positionを参照する必要がある）を直す必要がある。
- プラクティス個別ページのステータス変更が非同期に行われているのは他と整合性が取れないので同期にした方がよさそう。（リロードせずに一覧に移動などができない）

**Comment by Paru871** [comment]
@komagata @machida 
こちらのIssueは今年2月に本番環境で正常に表示できなかったため駒形さんにその後の調査と修正をお願いしたのですが、現在は本番環境で意図通りの場所にアンカーがついているようです。

↓下のスクショは私のプラクティス一覧ページです。最近始まったWebセキュリティのプラクティスにアンカーがついています。
![スクリーンショット 2022-07-04 17 11 13](https://user-images.githubusercontent.com/82434093/177139750-d8adcd6d-2415-493b-b079-50462371e5de.png)

駒形さん、ご対応いただきありがとうございます！(もしもまだ調査継続中でしたら引き続きよろしくお願いいたします🙇🏻‍♀️)
