### ISSUE TITLE
開発環境でニコニコカレンダーが表示されない場合がある

### ISSUE THREAD

**Issue by ot0m1** [fjordllc/bootcamp#4056]
## 概要

ローカルに`makrdown-it-anchor`がインストールされていない場合、以下のようなエラーが発生しニコニコカレンダー（自分は確認しきれていませんが、おそらく他にも`makrdown-it-anchor`を利用しているVueの箇所）が読み込めない。

```
markdown-it-headings.js:1 Uncaught Error: Cannot find module 'markdown-it-anchor'
    at webpackMissingModule (markdown-it-headings.js:1:1)
    at Module../app/javascript/markdown-it-headings.js (markdown-it-headings.js:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at Module../app/javascript/markdown-initializer.js (loading-list-placeholder.vue?c637:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at Module../app/javascript/markdown.js (markdown.js:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at Module../app/javascript/packs/application.js (application.js:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at bootstrap:83:1
webpackMissingModule @ markdown-it-headings.js:1
./app/javascript/markdown-it-headings.js @ markdown-it-headings.js:1
__webpack_require__ @ bootstrap:19
./app/javascript/markdown-initializer.js @ loading-list-placeholder.vue?c637:1
__webpack_require__ @ bootstrap:19
./app/javascript/markdown.js @ markdown.js:1
__webpack_require__ @ bootstrap:19
./app/javascript/packs/application.js @ application.js:1
__webpack_require__ @ bootstrap:19
（匿名） @ bootstrap:83
（匿名） @ bootstrap:83
```

## 再現手順

1. 開発環境に生徒のロールのアカウントでログイン。
2.  ダッシュボードにアクセス。
3. エラーが表示される。（ニコニコカレンダーが表示されない）

## 期待される振る舞い

ニコニコカレンダーが表示される

## スクリーンショット

![スクリーンショット 2022-01-27 0 36 51](https://user-images.githubusercontent.com/6190966/151294890-10661456-9174-4743-a3d1-5f77a50cad4d.png)

## 環境

 - OS: MacOS Monterey 12.1
 - ブラウザ: Chrome, Vivaldi
 - バージョン: Chrome:バージョン: 97.0.4692.99（Official Build） （x86_64）|  Vivaldi | 5.0.2497.48 (Stable channel) （x86_64）

## 補足
ローカルに`makrdown-it-anchor`をインストールするととりあえず解決します。

**Comment by ot0m1** [comment]
こちら僕の勘違いのようでした🙏
`yarn install` を実行した際に Boopcamp の package.json とは違うものを参照する場所で実行したために `yarn add` が必要であるかのような状況になっていました。

https://github.com/fjordllc/bootcamp/commit/b7d6cf5a0878d8e1ec838653af7353a4bc539338 のコミットを確認したところ package.json に markdown-it-anchor が明記されており、Boopcamp のディレクトリ内で `yarn install` を実行することでこの issue のエラーは解消されます。

**Comment by ot0m1** [comment]
https://discord.com/channels/715806612824260640/809595476847493192/937166184795758663 で @komagata さんへ報告しクローズ。
