### ISSUE TITLE
日報の追加時か変更時にDuplicationエラーが出ている

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4408]
本番環境で下記のエラーが出ているようです。出ないように日報の投稿時にユーザー（user_id）と投稿日時（reported_on）のセットがが既に重複してないか調べてから保存処理するようにお願いしたいです。

```

PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_reports_on_user_id_and_reported_on"
DETAIL:  Key (user_id, reported_on)=(609827778, 2022-02-25) already exists.

  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb", line 672, in exec_params
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb", line 672, in block (2 levels) in exec_no_cache
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies/interlock.rb", line 48, in block in permit_concurrent_loads
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/concurrency/share_lock.rb", line 187, in yield_shares
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies/interlock.rb", line 47, in permit_concurrent_loads
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb", line 671, in block in exec_no_cache
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/abstract_adapter.rb", line 696, in block (2 levels) in log
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb", line 26, in block (2 levels) in synchronize
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb", line 25, in handle_interrupt
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb", line 25, in block in synchronize
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb", line 21, in handle_interrupt
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb", line 21, in synchronize
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/abstract_adapter.rb", line 695, in block in log
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/notifications/instrumenter.rb", line 24, in instrument
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/abstract_adapter.rb", line 687, in log
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb", line 670, in exec_no_cache
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb", line 649, in execute_and_clear
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb", line 53, in exec_query
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb", line 136, in exec_insert
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb", line 91, in exec_insert
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb", line 171, in insert
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/abstract/query_cache.rb", line 22, in insert
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/persistence.rb", line 375, in _insert_record
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/persistence.rb", line 929, in _create_record
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/counter_cache.rb", line 166, in _create_record
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/locking/optimistic.rb", line 79, in _create_record
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/attribute_methods/dirty.rb", line 201, in _create_record
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/callbacks.rb", line 461, in block in _create_record
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/callbacks.rb", line 106, in run_callbacks
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/callbacks.rb", line 824, in _run_create_callbacks
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/callbacks.rb", line 461, in _create_record
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/timestamp.rb", line 108, in _create_record
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/persistence.rb", line 900, in create_or_update
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/callbacks.rb", line 457, in block in create_or_update
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/callbacks.rb", line 117, in block in run_callbacks
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/autosave_association.rb", line 385, in around_save_collection_association
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/callbacks.rb", line 126, in block in run_callbacks
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/callbacks.rb", line 137, in run_callbacks
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/callbacks.rb", line 824, in _run_save_callbacks
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/callbacks.rb", line 457, in create_or_update
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/timestamp.rb", line 126, in create_or_update
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/persistence.rb", line 474, in save
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/validations.rb", line 47, in save
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/transactions.rb", line 298, in block in save
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/transactions.rb", line 354, in block in with_transaction_returning_status
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb", line 320, in block in transaction
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/abstract/transaction.rb", line 319, in block in within_new_transaction
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb", line 26, in block (2 levels) in synchronize
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb", line 25, in handle_interrupt
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb", line 25, in block in s

**Comment by yocajii** [comment]
@komagata 
調査方法と対応の方針について相談させてください。

> 日報の投稿時にユーザー（user_id）と投稿日時（reported_on）のセットがが既に重複してないか調べてから保存処理する

下記のようにvalidationはすでに存在していて、念のため学習日が重複する日報の新規作成や更新を試しましたが、`@report.save`のタイミングで期待通りにvalidationが実行されてロールバックしました。
https://github.com/fjordllc/bootcamp/blob/1f6ad34927d4400e4925b65367e9ce9ef109f14d/app/models/report.rb#L33

```shell
TRANSACTION (0.3ms)  BEGIN
（中略）
  ↳ app/controllers/reports_controller.rb:70:in `update'
  Report Exists? (0.6ms)  SELECT 1 AS one FROM "reports" WHERE "reports
"."reported_on" = $1 AND "reports"."id" != $2 AND "reports"."user_id" =
 $3 LIMIT $4  [["reported_on", "2022-07-07"], ["id", 1066585820], ["use
r_id", 253826460], ["LIMIT", 1]]
  ↳ app/controllers/reports_controller.rb:70:in `update'
  TRANSACTION (0.2ms)  ROLLBACK
```

重複をチェックするとしたらvalidationになるかと考えたのですが、他に確認するべき処理などありましたらご教示いただけないでしょうか。

**Comment by komagata** [comment]
@yocajii なるほど〜。validationで弾かれる時はIssue本文のようなエラーは出ないので謎ですね〜。
ActiveRecordのmodelを通さず（validationがかからない）この辺りを更新してる処理もなさそうですし。

ではこの調査を持ってこのIssueは完了としてOKです〜！

**Comment by yocajii** [comment]
@komagata 
返信ありがとうございます🙇‍♂️
承知いたしました！このIssueはクローズいたします。
