### ISSUE TITLE
提出物が削除されたらそれについたコメントも削除したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#4568]
コメントが残った結果として検索の時の下記のようなエラーが出るので。

```

ActiveRecord::RecordNotFound: Couldn't find Product with 'id'=11731
  File "/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/core.rb", line 338, in find
  File "/app/app/helpers/search_helper.rb", line 6, in matched_document
  File "/app/app/views/api/searchables/_searchable.json.jbuilder", line 1, in _app_views_api_searchables__searchable_json_jbuilder___642618141061096964_358920
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/base.rb", line 247, in public_send
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/base.rb", line 247, in _run
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/template.rb", line 154, in block in render
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb", line 205, in instrument
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/template.rb", line 345, in instrument_render_template
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/template.rb", line 152, in render
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/renderer/partial_renderer.rb", line 285, in block in render_partial_template
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb", line 203, in block in instrument
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/notifications/instrumenter.rb", line 24, in instrument
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb", line 203, in instrument
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/renderer/partial_renderer.rb", line 280, in render_partial_template
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/renderer/partial_renderer.rb", line 271, in render
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/renderer/renderer.rb", line 81, in render_partial_to_object
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/renderer/renderer.rb", line 27, in render_to_object
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/renderer/renderer.rb", line 22, in render
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/helpers/rendering_helper.rb", line 38, in block in render
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/base.rb", line 273, in in_rendering_context
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/helpers/rendering_helper.rb", line 34, in render
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder/jbuilder_template.rb", line 180, in _render_partial
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder/jbuilder_template.rb", line 174, in _render_partial_with_options
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder/jbuilder_template.rb", line 262, in _render_explicit_partial
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder/jbuilder_template.rb", line 55, in partial!
  File "/app/app/views/api/searchables/index.json.jbuilder", line 3, in block (2 levels) in _app_views_api_searchables_index_json_jbuilder___1423424234067307076_358880
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder.rb", line 340, in block (2 levels) in _map_collection
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder.rb", line 347, in _scope
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder.rb", line 340, in block in _map_collection
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder.rb", line 339, in map
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder.rb", line 339, in _map_collection
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder.rb", line 217, in array!
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder/jbuilder_template.rb", line 123, in array!
  File "/app/app/views/api/searchables/index.json.jbuilder", line 2, in block in _app_views_api_searchables_index_json_jbuilder___1423424234067307076_358880
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder.rb", line 42, in block in set!
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder.rb", line 296, in block in _merge_block
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder.rb", line 347, in _scope
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder.rb", line 296, in _merge_block
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder.rb", line 42, in set!
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder/jbuilder_template.rb", line 133, in set!
  File "/usr/local/bundle/gems/jbuilder-2.11.5/lib/jbuilder.rb", line 70, in method_missing
  File "/app/app/views/api/searchables/index.json.jbuilder", line 1, in _app_views_api_searchables_index_json_jbuilder___1423424234067307076_358880
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/base.rb", line 247, in public_send
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/base.rb", line 247, in _run
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/template.rb", line 154, in block in render
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb", line 205, in instrument
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/template.rb", line 345, in instrument_render_template
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/template.rb", line 152, in render
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/renderer/template_renderer.rb", line 61, in block (2 levels) in render_template
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb", line 203, in block in instrument
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/notifications/instrumenter.rb", line 24, in instrument
  File "/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb", line 203, in instrument
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/renderer/template_renderer.rb", line 56, in block in render_template
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/renderer/template_renderer.rb", line 75, in render_with_layout
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/renderer/template_renderer.rb", line 55, in render_template
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/renderer/template_renderer.rb", line 11, in render
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/renderer/renderer.rb", line 61, in render_template_to_object
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/renderer/renderer.rb", line 29, in render_to_object
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/rendering.rb", line 117, in block in _render_template
  File "/usr/local/bundle/gems/actionview-6.1.4.4/lib/action_view/base.rb", line 273, in in_rendering_con

**Comment by SatoshiHaramura** [comment]
【確認したい現在の挙動】
　・提出物を削除した際に、その提出物についたコメントも削除されるのか。
【結論】
　・コメントも全て削除されているように見受けられる。


コードは、コメントに対して`dependent: :delete_all`となっている。
https://github.com/fjordllc/bootcamp/blob/ffc4de9ff7e4151cb9f413bfa36fa40d08c5b23b/app/models/concerns/commentable.rb#L7

ローカル環境で、提出物(id: 1033498648)を削除したときのログ。
一番最後の行で、提出物(id: 1033498648)のコメントが削除されている。
```
Started DELETE "/products/1033498648" for 127.0.0.1 at 2022-07-08 10:27:02 +0900
Processing by ProductsController#destroy as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]", "id"=>"1033498648"}
  User Load (1.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 679998234], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:30:in `init_user'
  Product Load (1.0ms)  SELECT "products".* FROM "products" WHERE "products"."id" = $1 LIMIT $2  [["id", 1033498648], ["LIMIT", 1]]
  ↳ app/controllers/products_controller.rb:96:in `find_my_product'
  TRANSACTION (1.7ms)  BEGIN
  ↳ app/controllers/products_controller.rb:70:in `destroy'
  Comment Destroy (1.3ms)  DELETE FROM "comments" WHERE "comments"."commentable_id" = $1 AND "comments"."commentable_type" = $2  [["commentable_id", 1033498648], ["commentable_type", "Product"]]
```

そのため、isuueで実現したいことを既に満たしているように思われるため、問題がなければcloseさせて頂きたい。

**Comment by komagata** [comment]
確認させて頂きました。OKです〜🙆‍♂️

**Comment by SatoshiHaramura** [comment]
ご確認頂きましたので、close致します。
