### ISSUE TITLE
`/buzz` でアクセスできるページを作成したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6401]
- `/buzz` は1ページ。
- ログインしなくてもアクセスできる。
- このページの編集は管理者とメンターだけができる。
- Markdown で書ける。
- layout は `welcome` を使う。
- 編集、作成ページの layout は `application` を使う。

デザインは machida がやります。

**Comment by djkazunoko** [comment]
@komagata @machida 

`/articles`のようなイメージであっていますでしょうか？
> /buzz は1ページ。

**Comment by machida** [comment]
@djkazunoko レイアウトの設定や編集権限は`/articles` と同じなのですが、`/articles` はページをたくさん持っているのに対して、`buzz` は1ページしかない、というのが違いになります。

@komagata 実装に関して何かありましたらお願いしますー

**Comment by djkazunoko** [comment]
📝5/15質問タイムmachidaさんより
・外部のブログのリンク集にしたい
・seedで最初からコンテンツが表示されてる状態(new, createいらない)
・resourceでshow, edit, updateのみで良い

**Comment by djkazunoko** [comment]
https://github.com/fjordllc/bootcamp/pull/6730 のリリース後に本番環境で以下のエラーが発生。

- `/buzz`(https://bootcamp.fjord.jp/buzz) にアクセスすると、`500: Internal Server Error`が表示される。

## エラーの原因
データが空の状態で`/buzz`にアクセスすると以下のエラーが出る
```
Started GET "/buzz" for ::1 at 2023-07-22 12:16:37 +0900
Processing by BuzzController#show as HTML
Creating scope :search_by_keywords_scope. Overwriting existing method User.search_by_keywords_scope.
  User Load (2.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 459775584], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:32:in `init_user'
  Buzz Load (1.3ms)  SELECT "buzzes".* FROM "buzzes" ORDER BY "buzzes"."id" ASC LIMIT $1  [["LIMIT", 1]]
  ↳ app/controllers/buzz_controller.rb:26:in `set_buzz'
  Rendering layout layouts/welcome.html.slim
  Rendering buzz/show.html.slim within layouts/welcome
  Rendered buzz/show.html.slim within layouts/welcome (Duration: 1.8ms | Allocations: 2010)
  Rendered layout layouts/welcome.html.slim (Duration: 2.0ms | Allocations: 2095)
Completed 500 Internal Server Error in 175ms (ActiveRecord: 17.6ms | Allocations: 78990)



ActionView::Template::Error (undefined method `body' for nil:NilClass

; @output_buffer.safe_concat(((::Temple::Utils.escape_html_safe((@buzz.body))).to_s));
                                                                      ^^^^^):
    21:                 | フィヨルドブートキャンプに言及している記事を集めています。
    22:         .article__body
    23:           .js-markdown-view.a-long-text.is-md
    24:             = @buzz.body
    25:       - if admin_or_mentor_login?
    26:         .card-footer
    27:           .card-main-actions

app/views/buzz/show.html.slim:24
app/controllers/buzz_controller.rb:9:in `show'
```
`@buzz`が`nil`でviewに渡るのが原因

## 修正案
`app/controllers/buzz_controller.rb`
```diff
def set_buzz
  @buzz = Buzz.first
+ @buzz ||= Buzz.create(body: 'test')
end
```

**Comment by djkazunoko** [comment]
本番環境で動作確認ができましたので、closeいたします。
