### ISSUE TITLE
イベント作成時に作成者をWatchにする機能のテストが失敗してしまう

### ISSUE THREAD

**Issue by ymmtd0x0b** [fjordllc/bootcamp#6719]
## 概要

イベント作成者を Watch中 にする機能のテストにてバリデーションエラーが発生するようです。

## 再現手順

`EventOrganizerWatcherTest` ６行目の `#call` をテスト実行すると再現できると思います。

```sh
❯ bin/rails test test/models/event_organizer_watcher_test.rb:6
Run options: --seed 14990

# Running:

E

Error:
EventOrganizerWatcherTest#test_#call:
ActiveRecord::RecordInvalid: バリデーションに失敗しました: Userはすでに存在します
    app/models/event_organizer_watcher.rb:5:in `call'
    test/models/event_organizer_watcher_test.rb:9:in `block (2 levels) in <class:EventOrganizerWatcherTest>'
    test/models/event_organizer_watcher_test.rb:8:in `block in <class:EventOrganizerWatcherTest>'


rails test test/models/event_organizer_watcher_test.rb:6


[Minitest::CI] Generating test report in JUnit XML format...


Finished in 3.119380s, 0.3206 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by ymmtd0x0b** [comment]
動作確認できましたので Close します 🙋‍♂️
