### ISSUE TITLE
通知ページが表示されない

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/bootcamp#7129]
https://bootcamp.fjord.jp/notifications?status=unread を開くと画面に何も表示されません。
consoleを見るといくつかエラーが表示されています。
![Screenshot 2023-12-12 at 9 07 48](https://github.com/fjordllc/bootcamp/assets/1148320/ab50cdc7-c6d1-43fb-9c8e-b9e1ec7a8766)

```
notifications_bell.vue:66 
        
        
       GET https://bootcamp.fjord.jp/api/notifications.json?status=unread 500 (Internal Server Error)
created @ notifications_bell.vue:66
Wr @ vue.runtime.esm.js:2846
ct @ vue.runtime.esm.js:3820
e._init @ vue.runtime.esm.js:5345
o @ vue.runtime.esm.js:5472
(anonymous) @ vue.runtime.esm.js:4317
init @ vue.runtime.esm.js:4168
(anonymous) @ vue.runtime.esm.js:6158
f @ vue.runtime.esm.js:6120
(anonymous) @ vue.runtime.esm.js:6631
e._update @ vue.runtime.esm.js:3559
a @ vue.runtime.esm.js:3660
e.get @ vue.runtime.esm.js:3252
e @ vue.runtime.esm.js:3242
e @ vue.runtime.esm.js:3681
ra.$mount @ vue.runtime.esm.js:8221
(anonymous) @ notifications_bell.js:9
rollbar.min.js:1 TypeError: Cannot read properties of undefined (reading 'forEach')
    at notifications_bell.vue:78:1
e.<computed> @ rollbar.min.js:1
(anonymous) @ notifications_bell.vue:83
Promise.catch (async)
created @ notifications_bell.vue:81
Wr @ vue.runtime.esm.js:2846
ct @ vue.runtime.esm.js:3820
e._init @ vue.runtime.esm.js:5345
o @ vue.runtime.esm.js:5472
(anonymous) @ vue.runtime.esm.js:4317
init @ vue.runtime.esm.js:4168
(anonymous) @ vue.runtime.esm.js:6158
f @ vue.runtime.esm.js:6120
(anonymous) @ vue.runtime.esm.js:6631
e._update @ vue.runtime.esm.js:3559
a @ vue.runtime.esm.js:3660
e.get @ vue.runtime.esm.js:3252
e @ vue.runtime.esm.js:3242
e @ vue.runtime.esm.js:3681
ra.$mount @ vue.runtime.esm.js:8221
(anonymous) @ notifications_bell.js:9
fetcher.js:2 
        
        
       GET https://bootcamp.fjord.jp/api/notifications.json?status=unread&page=1 500 (Internal Server Error)
a @ fetcher.js:2
(anonymous) @ index.esm.js:838
(anonymous) @ index.esm.js:119
(anonymous) @ index.esm.js:68
(anonymous) @ index.esm.js:42
n @ index.esm.js:24
(anonymous) @ index.esm.js:780
(anonymous) @ index.esm.js:1035
gs @ react-dom.production.min.js:4465
Dl @ react-dom.production.min.js:5478
r.unstable_runWithPriority @ scheduler.production.min.js:235
Yn @ react-dom.production.min.js:2345
Bl @ react-dom.production.min.js:5304
bl @ react-dom.production.min.js:5019
hl @ react-dom.production.min.js:4877
Kl @ react-dom.production.min.js:6052
(anonymous) @ react-dom.production.min.js:6139
wl @ react-dom.production.min.js:5048
ic @ react-dom.production.min.js:6138
r.render @ react-dom.production.min.js:6294
render @ renderHelpers.js:18
mountComponents @ index.js:115
handleMount @ index.js:144
rollbar.min.js:1 TypeError: Cannot read properties of undefined (reading 'length')
    at f (Notifications.jsx:50:33)
    at io (react-dom.production.min.js:3130:7)
    at Go (react-dom.production.min.js:3716:7)
    at zs (react-dom.production.min.js:5749:86)
    at Nl (react-dom.production.min.js:5262:11)
    at Sl (react-dom.production.min.js:5256:23)
    at Il (react-dom.production.min.js:5242:5)
    at bl (react-dom.production.min.js:5014:28)
    at react-dom.production.min.js:2368:18
    at r.unstable_runWithPriority (scheduler.production.min.js:235:12)
e.<computed> @ rollbar.min.js:1
us @ react-dom.production.min.js:4374
t.callback @ react-dom.production.min.js:4391
di @ react-dom.production.min.js:2606
gs @ react-dom.production.min.js:4500
Dl @ react-dom.production.min.js:5478
r.unstable_runWithPriority @ scheduler.production.min.js:235
Yn @ react-dom.production.min.js:2345
Bl @ react-dom.production.min.js:5304
bl @ react-dom.production.min.js:5019
(anonymous) @ react-dom.production.min.js:2368
r.unstable_runWithPriority @ scheduler.production.min.js:235
Yn @ react-dom.production.min.js:2345
zn @ react-dom.production.min.js:2365
Hn @ react-dom.production.min.js:2357
hl @ react-dom.production.min.js:4877
No @ react-dom.production.min.js:3466
(anonymous) @ index.esm.js:632
g @ index.esm.js:812
(anonymous) @ index.esm.js:939
(anonymous) @ index.esm.js:119
(anonymous) @ index.esm.js:68
o @ index.esm.js:27
Promise.then (async)
l @ index.esm.js:40
(anonymous) @ index.esm.js:42
n @ index.esm.js:24
(anonymous) @ index.esm.js:780
(anonymous) @ index.esm.js:1035
gs @ react-dom.production.min.js:4465
Dl @ react-dom.production.min.js:5478
r.unstable_runWithPriority @ scheduler.production.min.js:235
Yn @ react-dom.production.min.js:2345
Bl @ react-dom.production.min.js:5304
bl @ react-dom.production.min.js:5019
hl @ react-dom.production.min.js:4877
Kl @ react-dom.production.min.js:6052
(anonymous) @ react-dom.production.min.js:6139
wl @ react-dom.production.min.js:5048
ic @ react-dom.production.min.js:6138
r.render @ react-dom.production.min.js:6294
render @ renderHelpers.js:18
mountComponents @ index.js:115
handleMount @ index.js:144
Notifications.jsx:50 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at f (Notifications.jsx:50:33)
    at io (react-dom.production.min.js:3130:7)
    at Go (react-dom.production.min.js:3716:7)
    at zs (react-dom.production.min.js:5749:86)
    at Nl (react-dom.production.min.js:5262:11)
    at Sl (react-dom.production.min.js:5256:23)
    at Il (react-dom.production.min.js:5242:5)
    at bl (react-dom.production.min.js:5014:28)
    at react-dom.production.min.js:2368:18
    at r.unstable_runWithPriority (scheduler.production.min.js:235:12)
```

**Comment by JunichiIto** [comment]
そもそも右上のベルマークの通知の時点でエラーが出てるっぽい。
<img width="1368" alt="fbc" src="https://github.com/fjordllc/bootcamp/assets/1148320/ded557b1-9948-4075-a862-9ce6c6de22c4">

```
notifications_bell.vue:66 
        
        
       GET https://bootcamp.fjord.jp/api/notifications.json?status=unread 500 (Internal Server Error)
created @ notifications_bell.vue:66
Wr @ vue.runtime.esm.js:2846
ct @ vue.runtime.esm.js:3820
e._init @ vue.runtime.esm.js:5345
o @ vue.runtime.esm.js:5472
(anonymous) @ vue.runtime.esm.js:4317
init @ vue.runtime.esm.js:4168
(anonymous) @ vue.runtime.esm.js:6158
f @ vue.runtime.esm.js:6120
(anonymous) @ vue.runtime.esm.js:6631
e._update @ vue.runtime.esm.js:3559
a @ vue.runtime.esm.js:3660
e.get @ vue.runtime.esm.js:3252
e @ vue.runtime.esm.js:3242
e @ vue.runtime.esm.js:3681
ra.$mount @ vue.runtime.esm.js:8221
(anonymous) @ notifications_bell.js:9
rollbar.min.js:1 TypeError: Cannot read properties of undefined (reading 'forEach')
    at notifications_bell.vue:78:1
e.<computed> @ rollbar.min.js:1
(anonymous) @ notifications_bell.vue:83
Promise.catch (async)
created @ notifications_bell.vue:81
Wr @ vue.runtime.esm.js:2846
ct @ vue.runtime.esm.js:3820
e._init @ vue.runtime.esm.js:5345
o @ vue.runtime.esm.js:5472
(anonymous) @ vue.runtime.esm.js:4317
init @ vue.runtime.esm.js:4168
(anonymous) @ vue.runtime.esm.js:6158
f @ vue.runtime.esm.js:6120
(anonymous) @ vue.runtime.esm.js:6631
e._update @ vue.runtime.esm.js:3559
a @ vue.runtime.esm.js:3660
e.get @ vue.runtime.esm.js:3252
e @ vue.runtime.esm.js:3242
e @ vue.runtime.esm.js:3681
ra.$mount @ vue.runtime.esm.js:8221
(anonymous) @ notifications_bell.js:9
```

**Comment by komagata** [comment]
こちら緊急リリースをして修正致しました。
