### ISSUE TITLE
メンターがコメントを削除したときにmentor_last_commented_atが空になっていない

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7144]
https://github.com/fjordllc/bootcamp/blob/main/app/models/product.rb#L193

↑この辺りでcommentがひとつもない場合にmentor_last_commented_atを空にできてないのが問題だと思う。

空になっていないと↓のようなことが起こる。

https://github.com/fjordllc/bootcamp/issues/6965#issuecomment-1830515168

**Comment by junohm410** [comment]
@komagata 
お疲れ様です。
現在、本件を調査中ですが、現在の`main`での開発環境上では、

> ↑この辺りでcommentがひとつもない場合にmentor_last_commented_atを空にできてないのが問題だと思う。

> メンターがコメントを削除したときにmentor_last_commented_atが空になっていない

↑これらのような状況ではなく、コメント削除後にコメントがひとつもない場合でも、`mentor_last_commented_at`を空にできているように見えます。

## 検証した状態と、その結果
1. http://localhost:3000/products/613458348
（デフォルトではコメントがない提出物）に`mentormentarou`でログイン
2. 1件目のコメントを投稿して、`mentor_last_commented_at`に値が入ったことをRails consoleで確認する
3. ↑でつけたコメントを削除すると、`mentor_last_commented_at`が`nil`になっていることをRails consoleで確認する

### 2の時点での当該日報の状況
```                                                                         
 id: 613458348,                                                                                        
 practice_id: 315059988,                                                                               
 user_id: 301971253,                                                                                   
 body: "研修の提出物です。",                                                                           
 created_at: Thu, 14 Dec 2023 11:39:28.000000000 JST +09:00,                                           
 updated_at: Sat, 06 Jan 2024 11:21:18.902339000 JST +09:00,                                           
 wip: false,                                                       
 published_at: Thu, 14 Dec 2023 11:39:28.000000000 JST +09:00,     
 checker_id: 534981761,                                            
 self_last_commented_at: nil,                                      
 mentor_last_commented_at: Sat, 06 Jan 2024 14:24:05.795615000 JST +09:00,　#更新されている
 commented_at: Sat, 06 Jan 2024 14:24:05.795615000 JST +09:00>     
```
### 3の時点での当該日報の状況
```
 id: 613458348,          
 practice_id: 315059988,
 user_id: 301971253,
 body: "研修の提出物です。",
 created_at: Thu, 14 Dec 2023 11:39:28.000000000 JST +09:00,
 updated_at: Sat, 06 Jan 2024 11:21:18.902339000 JST +09:00,
 wip: false,
 published_at: Thu, 14 Dec 2023 11:39:28.000000000 JST +09:00,
 checker_id: 534981761,
 self_last_commented_at: nil,
 mentor_last_commented_at: nil,　#nilになっている
 commented_at: nil>
```

### 3を実行（コメント削除）した時のログ
```
14:26:36 rails.1     | Started DELETE "/api/comments/1065438867.json" for 127.0.0.1 at 2024-01-06 14:26:36 +0900
14:26:36 rails.1     | Processing by API::CommentsController#destroy as JSON
14:26:36 rails.1     |   Parameters: {"id"=>"1065438867"}
14:26:36 rails.1     |   User Load (2.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 534981761], ["LIMIT", 1]]
14:26:36 rails.1     |   ↳ app/controllers/application_controller.rb:33:in `init_user'
14:26:37 rails.1     |   Comment Load (1.4ms)  SELECT "comments".* FROM "comments" WHERE "comments"."user_id" = $1 AND "comments"."id" = $2 LIMIT $3  [["user_id", 534981761], ["id", 1065438867], ["LIMIT", 1]]
14:26:37 rails.1     |   ↳ app/controllers/api/comments_controller.rb:54:in `set_my_comment'
14:26:37 rails.1     |   TRANSACTION (1.1ms)  BEGIN
14:26:37 rails.1     |   ↳ app/controllers/api/comments_controller.rb:40:in `destroy'
14:26:37 rails.1     |   Reaction Destroy (1.7ms)  DELETE FROM "reactions" WHERE "reactions"."reactionable_id" = $1 AND "reactions"."reactionable_type" = $2  [["reactionable_id", 1065438867], ["reactionable_type", "Comment"]]
14:26:37 rails.1     |   ↳ app/controllers/api/comments_controller.rb:40:in `destroy'
14:26:37 rails.1     |   Comment Destroy (1.1ms)  DELETE FROM "comments" WHERE "comments"."id" = $1  [["id", 1065438867]]
14:26:37 rails.1     |   ↳ app/controllers/api/comments_controller.rb:40:in `destroy'
14:26:37 rails.1     |   Product Load (1.9ms)  SELECT "products".* FROM "products" WHERE "products"."id" = $1 LIMIT $2  [["id", 613458348], ["LIMIT", 1]]
14:26:37 rails.1     |   ↳ app/models/comment/after_destroy_callback.rb:5:in `after_destroy'
14:26:37 rails.1     |   Comment Load (0.8ms)  SELECT "comments".* FROM "comments" WHERE "comments"."commentable_id" = $1 AND "comments"."commentable_type" = $2 ORDER BY "comments"."id" DESC LIMIT $3  [["commentable_id", 613458348], ["commentable_type", "Product"], ["LIMIT", 1]]
14:26:37 rails.1     |   ↳ app/models/product.rb:192:in `delete_last_commented_at'
# ↓ここでmentor_last_commented_atをnilにしている
14:26:37 rails.1     |   Product Update (1.5ms)  UPDATE "products" SET "mentor_last_commented_at" = $1, "self_last_commented_at" = $2 WHERE "products"."id" = $3  [["mentor_last_commented_at", nil], ["self_last_commented_at", nil], ["id", 613458348]]
14:26:37 rails.1     |   ↳ app/models/product.rb:183:in `update_last_commented_at'
14:26:37 rails.1     |   Comment Load (0.9ms)  SELECT "comments".* FROM "comments" WHERE "comments"."commentable_id" = $1 AND "comments"."commentable_type" = $2 ORDER BY "comments"."id" DESC LIMIT $3  [["commentable_id", 613458348], ["commentable_type", "Product"], ["LIMIT", 1]]
14:26:37 rails.1     |   ↳ app/models/product.rb:196:in `delete_commented_at'
14:26:37 rails.1     |   Product Update (2.2ms)  UPDATE "products" SET "commented_at" = $1 WHERE "products"."id" = $2  [["commented_at", nil], ["id", 613458348]]
14:26:37 rails.1     |   ↳ app/models/product.rb:188:in `update_commented_at'
14:26:37 rails.1     |   Comment Exists? (1.0ms)  SELECT 1 AS one FROM "comments" WHERE "comments"."commentable_id" = $1 AND "comments"."commentable_type" = $2 AND (created_at > '2024-01-06 05:24:05.795615') LIMIT $3  [["commentable_id", 613458348], ["commentable_type", "Product"], ["LIMIT", 1]]
14:26:37 rails.1     |   ↳ app/models/comment.rb:60:in `later_exists?'
14:26:37 rails.1     |   Comment Load (1.0ms)  SELECT "comments".* FROM "comments" WHERE "comments"."commentable_id" = $1 AND "comments"."commentable_type" = $2 AND (created_at < '2024-01-06 05:24:05.795615') ORDER BY "comments"."created_at" DESC LIMIT $3  [["commentable_id", 613458348], ["commentable_type", "Product"], ["LIMIT", 1]]
14:26:37 rails.1     |   ↳ app/models/comment.rb:46:in `previous'
14:26:37 rails.1     |   User Update (0.9ms)  UPDATE "users" SET "updated_at" = $1 WHERE "users"."id" = $2  [["updated_at", "2024-01-06 05:26:37.021960"], ["id", 534981761]]
14:26:37 rails.1     |   ↳ app/controllers/api/comments_controller.rb:40:in `destroy'
14:26:37 rails.1     |   TRANSACTION (1.3ms)  COMMIT
14:26:37 rails.1     |   ↳ app/controllers/api/comments_controller.rb:40:in `destroy'
14:26:37 rails.1     | No template found for API::CommentsController#destroy, rendering head :no_content
14:26:37 rails.1     |   User Update All (1.4ms)  UPDATE "users" SET "last_activity_at" = $1 WHERE "users"."id" = $2  [["last_activity_at", "2024-01-06 05:26:37.060218"], ["id", 534981761]]
14:26:37 rails.1     | Completed 204 No Content in 99ms (ActiveRecord: 26.1ms | Allocations: 18633)
14:26:37 rails.1     |
14:26:37 rails.1     |
```

日報上のコメントが削除されたときは、Commentモデルが定義するコールバック`after_destroy Comment::AfterDestroyCallback.new`が発火し、その中で`mentor_last_commented_at`の更新作業を行います。

```ruby
# Comment::AfterDestroyCallback

class Comment::AfterDestroyCallback
  def after_destroy(comment)
    return unless comment.commentable.instance_of?(Product)

    #ここでmentor_last_commented_atを、「コメント削除後」の最新のコメントの内容で更新する
    comment.commentable.delete_last_commented_at
    comment.commentable.delete_commented_at
    delete_product_cache(comment.commentable.id)

    return unless comment.latest?

    delete_assigned_and_unreplied_product_count_cache(comment)
  end
```

```ruby
# Productモデル
# 中略

  def update_last_commented_at(comment)
    if comment
      if comment.user.mentor
        update_columns(mentor_last_commented_at: comment.updated_at) # rubocop:disable Rails/SkipsModelValidations
      elsif comment.user == user
        update_columns(self_last_commented_at: comment.updated_at) # rubocop:disable Rails/SkipsModelValidations
      end
    else #コメントの削除の結果、その日報のコメントが0件になったときの条件分岐
      update_columns(mentor_last_commented_at: nil, self_last_commented_at: nil) # rubocop:disable Rails/SkipsModelValidations
    end
  end

# 中略

  def delete_last_commented_at
    update_last_commented_at(comments.last) #「コメント削除後」の最新のコメントの内容で更新する
  end
```

コメントを削除した結果、その日報にコメントがなくなった場合（`update_last_commented_at(comments.last)`の引数が`nil`のとき）は、上の条件分岐の結果、`mentor_last_commented_at`は`nil`に更新されます。
ログでも、これに沿った流れが正常に実行されているように見えました。

## シェアいただきたいこと
調査を進める上で、下記の点をシェアいただけないでしょうか？

- komagataさんが、コメント削除時にコメントがなくなったときに`mentor_last_commented_at`が空にならないとにらんだ理由や状況など（もしあれば）
- 上記の再現の中で気になった点や、私の理解がおかしそうな点

ご確認のほど、何卒よろしくお願い申し上げます🙏

**Comment by komagata** [comment]
@junohm410 なるほど〜
だとすると本番環境で下記のようなデータがあったのが謎ですね〜

https://github.com/fjordllc/bootcamp/issues/6965#issuecomment-1830515168

**Comment by junohm410** [comment]
@komagata 
ご返信ありがとうございました🙏

> だとすると本番環境で下記のようなデータがあったのが謎ですね〜
https://github.com/fjordllc/bootcamp/issues/6965#issuecomment-1830515168

`Product.where.not(commented_at: nil)`で絞った先の処理でエラーが起きている、ということは、`mentor_last_commented_at`というよりは、やはり`commented_at`属性まわりの問題なのかなと感じています。

```rb
# Commentモデル

  scope :unchecked_no_replied_products, lambda {
    self_last_commented_products = where.not(commented_at: nil).filter do |product|
      #ここでproduct.comments.lastがnilになるデータがあってエラーになる
      product.comments.last.user_id == product.user.id
    end
```

上記の検証の中では、メンターが提出物へのコメントを消した際にコメントが0件になったときは、`commented_at`も空にできているので、なぜ「コメントがないのに、`commented_at`が空ではない提出物」が存在するのかは、まだ解明できていませんが……

> 本番環境でコメントが無い提出物にmentor_last_commented_atが残っていたからですが

そうだったのですね。ちなみに、その提出物の`commented_at`はどうなっているか、確認していただくことは可能でしょうか？（空なのか、特定の日付が入っているのか）

**Comment by komagata** [comment]
@junohm410 

> - その提出物のcommented_atはどうなっているか（空なのか、特定の日付が入っているのか）
> - その提出物のユーザーが休会者・現役生のどちらか？

どのデータだったかはわからないです。（すみません、情報をもっと残しておけばよかったですね）

これ以上の調査は難しいと思うので、こちらは調査のIssueということでこれで完了にしたいと思います。
間違った情報を与えてしまってすみません。（ポイントはゲットでOKです〜）

**Comment by junohm410** [comment]
@komagata
承知しました！
提出物へのコメントの削除の流れを理解したり、コールバッククラスの勉強になりました🙏
こまかくご返信いただき、ありがとうございました🙏

**Comment by junohm410** [comment]
※2024/1/17のふりかえりMTGで、このIssue上のコメントでご相談・ご報告した内容を共有しました。
また、本IssueについてはこれでCloseとする旨きまりましたので、私の方でCloseさせていただきます。
