### ISSUE TITLE
メンターダッシュボードに表示しているn日経過の提出物一覧を非vue化したい。

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#7947]
メンターでログインしたときにダッシュボードに表示されるこれが今はVueで実装されているので、Railsのviewに移行する。

<img width="375" alt="貼り付けた画像_2024_07_09_20_02" src="https://github.com/fjordllc/bootcamp/assets/168265/a102d975-5a74-4409-bbf5-edae6bd6efc5">

**Comment by Shrimprin** [comment]
### 📝  関連するPR
* [【メンター向け】ダッシュボードに5日以上経過した提出物を表示する#4908](https://github.com/fjordllc/bootcamp/pull/4908)

**Comment by Shrimprin** [comment]
@komagata @machida 
お疲れ様です。
本イシューでは既存のVueをRailsのViewComponentへ置き換えをしています。
ViewCompoentのテストの実装で上手くいかない点があり、アドバイスをいただけますでしょうか 🙇 

## 解決したいこと
ViewComponentのテストでActiveDecoratorメソッドが`undefined method`エラーとなる。
（以下、`ViewComponentのテスト = コンポーネントテスト` と記載します）

## エラー内容
例えば、ViewComponentの`html`ファイルで`user.icon_title`を呼び出す部分で以下のようなエラーが発生する。
エラーが発生するのはコンポーネントテストから呼び出した時のみで、テスト以外（ブラウザから呼び出す）はエラーは発生しない。

``` bash
❯ rails test test/components/product/product_component_test.rb
Running via Spring preloader in process 11715
Run options: --seed 21297

# Running:

....E

Error:
Products::ProductComponentTest#test_render_comments_count_when_there_are_comments:
NoMethodError: undefined method `icon_title' for #<User id: ...
...
{中略}
...
    app/components/products/product_component.html.slim:71:in `block in call'
    app/components/products/product_component.html.slim:69:in `call'
    test/components/product/product_component_test.rb:67:in `test_render_comments_count_when_there_are_comments'


rails test test/components/product/product_component_test.rb:64
```

<details>
<summary>全文</summary>

``` bash
❯ rails test test/components/product/product_component_test.rb
Running via Spring preloader in process 11715
Run options: --seed 21297

# Running:

....E

Error:
Products::ProductComponentTest#test_render_comments_count_when_there_are_comments:
NoMethodError: undefined method `icon_title' for #<User id: 459775584, login_name: "komagata", email: "komagata@fjord.jp", crypted_password: "$2a$10$n/xv4/1luueN6plzm2OyDezWlZFyGHjQEf4hwAW1r3k...", salt: "zW3kQ9ubsxQQtzzzs4ap", created_at: "2014-01-01 09:00:01.000000000 +0900", updated_at: "2024-09-26 18:37:04.934627000 +0900", remember_me_token: nil, remember_me_token_expires_at: nil, twitter_account: "komagata", facebook_url: "https://www.facebook.com/fjordllc/komagata1111", blog_url: "http://komagata.org", company_id: 636488896, description: "平日１０〜１９時勤務です。", accessed_at: nil, github_account: "komagata", adviser: false, nda: true, reset_password_token: nil, reset_password_token_expires_at: nil, reset_password_email_sent_at: nil, mentor: true, graduated_on: nil, course_id: 829913840, retired_on: nil, admin: true, job: "office_worker", organization: "株式会社ロッカ", os: "mac", experience: nil, retire_reason: nil, trainee: false, free: false, customer_id: nil, job_seeking: false, subscription_id: nil, mail_notification: true, job_seeker: false, github_id: nil, github_collaborator: true, name: "Komagata Masaki", name_kana: "コマガタ マサキ", satisfaction: nil, opinion: nil, retire_reasons: 0, unsubscribe_email_token: "037i-ef5n7V4EnPv74mtyQ", mentor_memo: nil, after_graduation_hope: nil, training_ends_on: nil, sad_streak: true, last_sad_report_id: 354780143, last_activity_at: "2014-01-01 09:00:01.000000000 +0900", hibernated_at: nil, profile_name: "駒形 真幸", profile_job: "エンジニア", profile_text: "株式会社ロッカの代表兼エンジニア。Rubyが大好きで怖話、フィヨルドブートキャンプなどを開発している...", feed_url: "https://example3.com/index.rdf", sent_student_followup_message: false, country_code: nil, subdivision_code: nil, auto_retire: true, editor: nil, other_editor: nil, invoice_payment: false, hide_mentor_profile: false, experiences: 6, tag_list: nil>
    app/components/products/product_component.html.slim:71:in `block in call'
    app/components/products/product_component.html.slim:69:in `call'
    test/components/product/product_component_test.rb:67:in `test_render_comments_count_when_there_are_comments'


rails test test/components/product/product_component_test.rb:64
```
</details>


## 調べたこと
### ActiveDecorator
- `active_decorator` gemによって導入される
- `app/decorators/user_decorator.rb`などのファイルで定義されている
- ビューでよく使う表示ロジックやフォーマットを記述する
- モデルとビューどちらにも記述できるロジックをデコレーターに記述することで、モデルとビューをスリムに保つことができる

### ViewComponentのテストでのActiveDecoratorの利用
- コンポーネントテストではActiveDecoratorは自動的には読み込まれないが、`user = user.extend(UserDecorator)`とすることでインスタンスからデコレーメソッドの呼び出せる
- デコレータを呼び出せるようにしたいインスタンスが別のインスタンスのアソシエーションを介す場合は、`product.user = product.user.extend(UserDecorator)`とすることでデコレータメソッドを呼び出せる

## エラーが発生するパターン
以下のように、rbファイルでデコレーターを適用した`user`で`product`に`comment`を作成した後、html側で`comment`から`user`を取得してデコレーターメソッドを呼び出そうとすると、`undefined method`となる。

- ViewComponentのrbファイル
``` rb
commented_user = users(:hogetaro).extend(UserDecorator)
@unassigned_product.comments.create!(user: commented_user, description: 'コメントを追加')
```

- ViewComponentのhtmlファイル
``` rb
product.comments.each do |comment|
	comment.user.icon_title # icon_titleがデコレーターメソッド
end
```

## 対応方法
対応方法を検討しましたのでご助言お願いできますでしょうか。
1. ViewComponentのロジック部分とActiveDecoratorは`モデルとビューをスリムにするためにロジックを記述する場所`という役割が被っているという認識です。ViewComponentではデコレーターメソッドは使わずにコンポーネントのロジック部分に代わりにそのロジックを記述すべきなのでしょうか？
2. システムテストでは明示的に`extend(HogeDecorator)`でデコレーターを適用しないでもデコレーターメソッドが利用できます。コンポーネントテストでも同様のことが可能なのであればその方法をご教授いただけますでしょうか？

以上、お手数ですがご回答をお願いいたします。

**Comment by Shrimprin** [comment]
[日報のコメント](https://bootcamp.fjord.jp/reports/101967)でで@reckyyさんからアドバイスいただいたので、3つ目の対応案として追加させてください。
とてもシンプルに記述できるため、この方法で対応で良いでしょうか？

### 対応方法（続き）
3. `product.commented_users.extend(UserDecorator)`で`users`にまとめてデコレーターを適用させる
``` rb
  def test_render_comments_count_when_there_are_comments
    commented_user = users(:komagata) #この時点でのextendは不要
    unassigned_product = decorate_product_user(products(:product6))
    unassigned_product.comments.create!(user: commented_user, description: 'コメントを追加')
    unassigned_product.commented_users.extend(UserDecorator)
    render_inline(Products::ProductComponent.new(
                    product: unassigned_product,
                    is_mentor: @is_mentor,
                    current_user_id: @current_user_id
                  ))

  end
```

**Comment by komagata** [comment]
@Shrimprin 

> 1. ViewComponentのロジック部分とActiveDecoratorはモデルとビューをスリムにするためにロジックを記述する場所という役割が被っているという認識です。ViewComponentではデコレーターメソッドは使わずにコンポーネントのロジック部分に代わりにそのロジックを記述すべきなのでしょうか？
> 2. システムテストでは明示的にextend(HogeDecorator)でデコレーターを適用しないでもデコレーターメソッドが利用できます。コンポーネントテストでも同様のことが可能なのであればその方法をご教授いただけますでしょうか？

2でお願いします。もうちょっと調べてみてください〜

**Comment by Shrimprin** [comment]
@komagata 
お疲れ様です！
Active Recordの`after_find`コールバックを使ってデコレーターを適用するヘルパーを作成して、問題を対処できるようにしました。
以下のような実装方針で良いかご助言お願いできますでしょうか。

- デコレーターを適用するヘルパー
https://github.com/fjordllc/bootcamp/blob/51a6fe0f6d6eb43d3c9b5b775c0912ffb44a022e/test/supports/decorator_helper.rb#L3-L7

- コンポーネントテストでの使用方法
コンポーネントテストの`setup`メソッドで以下のようにして呼び出します。
``` rb
require 'test_helper'
require 'supports/decorator_helper' # ヘルパーをrequireする

class Products::ProductsComponentTest < ViewComponent::TestCase
  def setup
    DecoratorHelper.auto_decorate(User) # デコレーターを適用したいモデルを引数で渡す
    # その他の処理
  end

  # テスト
end
```

これにより`User`レコードを読み込むたびにデコレーターが適用され、テスト内で毎回`extend(UserDecorator)`しなくて済みます。

### 参考
- [Railsガイド after_initializeとafter_find](https://railsguides.jp/active_record_callbacks.html#after-initialize%E3%81%A8after-find)

**Comment by komagata** [comment]
いいと思います。ただ下記に似たコードがあるので何かしら共通化できるといいかもですね。

[bootcamp/test/active\_decorator\_test\_case\.rb at main · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/blob/main/test/active_decorator_test_case.rb)

**Comment by Shrimprin** [comment]
@komagata 
ありがとうございます。
共通化も含めてPRを作成していきます。

**Comment by Shrimprin** [comment]
@machida さんに本番環境で確認いただいたためcloseとします。
