### ISSUE TITLE
不要な app/views/practices/_tab.html.slim を削除

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#8042]
app/views/practices/_tab.html.slim
は使われていないので削除する。

**Comment by Ryooo-k** [comment]
@komagata @machida 
質問がありますので、下記ご確認お願いいたします。

# 起こっている事象

mainブランチで`rails test:all`を実行すると、` 3 failures, 2 errors`の結果となっています。

<details>
<summary>テスト実行結果</summary>

```
$ rails test:all      
Run options: --seed 19687

# Running:

............................................................................................................................................................................................................................................................................................................................................[Screenshot Image]: /Users/ryo/FBC/bootcamp/tmp/screenshots/failures_test_show-hide_the_progress_of_others.png
F

Failure:
Course::PracticesTest#test_show/hide_the_progress_of_others [/Users/ryo/FBC/bootcamp/test/system/course/practices_test.rb:20]:
Expected false to be truthy.


rails test test/system/course/practices_test.rb:11

............................................................................................................................................................[Screenshot Image]: /Users/ryo/FBC/bootcamp/tmp/screenshots/failures_test_can_upload_heic_image_as_user_avatar.png
F

Failure:
UsersTest#test_can_upload_heic_image_as_user_avatar [/Users/ryo/FBC/bootcamp/test/system/users_test.rb:589]:
Expected /253826460\.png$/ to match "http://127.0.0.1:49183/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhjakJtT0dkaGVERnVkR05sTUhvNWRqUndaMmxyTkRKaloyUmxkQVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpVTJsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SW1obGFXTXRjMkZ0Y0d4bExXWnBiR1V1Y0c1bklqc2dabWxzWlc1aGJXVXFQVlZVUmkwNEp5ZG9aV2xqTFhOaGJYQnNaUzFtYVd4bExuQnVad1k3QmxRNkVXTnZiblJsYm5SZmRIbHdaVWtpRG1sdFlXZGxMM0J1WndZN0JsUTZFWE5sY25acFkyVmZibUZ0WlRvSmRHVnpkQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2tleSJ9fQ==--2bfb1e849b4dc719e0db0d4dba1263925de66d96/heic-sample-file.png".


rails test test/system/users_test.rb:579

.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................E

Error:
ProductsTest#test_admin_can_delete_a_product:
ActiveRecord::RecordNotFound: Couldn't find Product with 'id'=728267494
    app/controllers/api/comments_controller.rb:50:in `commentable'
    app/controllers/api/comments_controller.rb:9:in `index'


rails test test/system/products_test.rb:192

.........................[Screenshot Image]: /Users/ryo/FBC/bootcamp/tmp/screenshots/failures_test_not_display_learning_completion_message_when_a_user_of_the_completed_product_visits_after_the_second_time.png
F

Failure:
ProductsTest#test_not_display_learning_completion_message_when_a_user_of_the_completed_product_visits_after_the_second_time [/Users/ryo/FBC/bootcamp/test/system/products_test.rb:58]:
expected not to find text "喜びをXにポストする！" in "お知らせ\nプラクティス\n日報・ブログ\n15\nQ&A\nDocs\nポートフォリオ\nユーザー\nイベント\n相談\nすべて\nお知らせ\nプラクティス\n日報\n提出物\nQ&A\nDocs\nイベント\n定期イベント\nユーザー\nヘルプ\nMe\n3\n通知\nプラクティス「aptの基礎を覚える」を修了しました🎉\n喜びをXにポストする！\n閉じる\naptの基礎を覚える\nプラクティス一覧\nプラクティス\n日報 （0）\n質問 （0）\nDocs （0）\n提出物\n7日以内にメンターがレビューしますので、次のプラクティスにお進みください。\nもし、7日以上経ってもレビューされない場合は、メンターにお問い合わせください。\nこのプラクティスは修了しました🎉\nXに修了ポストする\nkimura (キムラ タダシ)\naptの基礎を覚えるの提出物\n提出\n2024年09月24日(火) 13:28\n更新\n2024年09月24日(火) 13:28\nコメント（\n0\n）\nWatch\nBookmark\nRaw\nプラクティスを確認\n終了条件を確認\n提出物\nプラクティス完了メッセージ未表示の提出物です。\n内容修正\n削除申請\nプラクティスに戻る\nコメント\nコメント\nプレビュー\nファイルを挿入\nコメントする\nホームページ\nブログ\n参考書籍\nGitHub Projects\nグッズ購入\nアンチハラスメントポリシー\n利用規約\nプライバシーポリシー\n特定商取引法に基づく表記\nコース一覧\n企業一覧\n#fjordbootcamp\nFjord Choice\nBuzzcord\nDiscordBotF\nFBC Stack\nLokka Inc.2012 - 2024"


rails test test/system/products_test.rb:52

...............................................................................................................................................................................................................................................................................................................................................................................[Screenshot Image]: /Users/ryo/FBC/bootcamp/tmp/screenshots/failures_test_display_replied_products_if_click_on_self_assigned_all-button.png
.E

Error:
Product::SelfAssignedTest#test_display_replied_products_if_click_on_self_assigned_all-button:
Selenium::WebDriver::Error::UnexpectedAlertOpenError: unexpected alert open: {Alert text : 提出物の担当になりました。}
  (Session info: chrome-headless-shell=129.0.6668.59)
    test/system/product/self_assigned_test.rb:143:in `block in <class:SelfAssignedTest>'


rails test test/system/product/self_assigned_test.rb:126

.............................................................................................................................................................................................................................................................................................................................................................................................................................................................
[Minitest::CI] Generating test report in JUnit XML format...


Finished in 855.318742s, 2.1279 runs/s, 5.9381 assertions/s.
1820 runs, 5079 assertions, 3 failures, 2 errors, 0 skips
```

</details>


# 質問内容

本issueの作業を始める前に、mainブランチで失敗したテストの修正から行うべきでしょうか。

**Comment by Ryooo-k** [comment]
@komagata @machida
上記の質問ですが、下記の対応にて対処できましたので、質問はキャンセルさせていただきます。

# 通過したテスト

- rails test test/system/course/practices_test.rb:11
- rails test test/system/products_test.rb:192
- rails test test/system/products_test.rb:52
- rails test test/system/product/self_assigned_test.rb:126

上記４つのテストは個別テストを実行してテスト通過すること確認しました。

# 失敗したテスト

- rails test test/system/users_test.rb:579

こちらのテストは個別テストでも失敗したのですが、[アバターファイル名をuser\_idにする by rira100000000 · Pull Request \#7751 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/7751)で対応中と把握しました。

**Comment by komagata** [comment]
@Ryooo-k Flakyなテストがいくつかあるので、ローカルでは実行するたびに成功しないテストがあるかもです。
少なくともCircleCI上では全てのテストが通る状態であれば大丈夫です。（CircleCI上で何度実行しても一回も成功しないテストが一つでも存在する場合は修正する必要があります）

**Comment by Ryooo-k** [comment]
@komagata 

> Flakyなテストがいくつかあるので、ローカルでは実行するたびに成功しないテストがあるかもです。
少なくともCircleCI上では全てのテストが通る状態であれば大丈夫です。

承知しました！何度やっても成功しなかったので、疑問に思って質問させていただきました。
CircleCI上で何度実行しても一回も成功しないテストが存在する場合は、修正するようにいたします。

**Comment by Ryooo-k** [comment]
不要なファイルの削除のみで動作確認はないためcloseいたします。
